/*
Opal API

Testing OnCallSchedulesApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package opal

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/opalsecurity/opal-go"
)

func Test_opal_OnCallSchedulesApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OnCallSchedulesApiService CreateOnCallSchedule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OnCallSchedulesApi.CreateOnCallSchedule(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OnCallSchedulesApiService GetOnCallSchedule", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var onCallScheduleId string

		resp, httpRes, err := apiClient.OnCallSchedulesApi.GetOnCallSchedule(context.Background(), onCallScheduleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OnCallSchedulesApiService GetOnCallSchedules", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OnCallSchedulesApi.GetOnCallSchedules(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
