/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"fmt"
)

// PaladinContextSourceProvider The integration a Paladin context source comes from.
type PaladinContextSourceProvider string

// List of PaladinContextSourceProvider
const (
	PALADINCONTEXTSOURCEPROVIDER_SLACK PaladinContextSourceProvider = "SLACK"
	PALADINCONTEXTSOURCEPROVIDER_NOTION PaladinContextSourceProvider = "NOTION"
	PALADINCONTEXTSOURCEPROVIDER_CONFLUENCE PaladinContextSourceProvider = "CONFLUENCE"
)

// All allowed values of PaladinContextSourceProvider enum
var AllowedPaladinContextSourceProviderEnumValues = []PaladinContextSourceProvider{
	"SLACK",
	"NOTION",
	"CONFLUENCE",
}

func (v *PaladinContextSourceProvider) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PaladinContextSourceProvider(value)
	for _, existing := range AllowedPaladinContextSourceProviderEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PaladinContextSourceProvider", value)
}

// NewPaladinContextSourceProviderFromValue returns a pointer to a valid PaladinContextSourceProvider
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPaladinContextSourceProviderFromValue(v string) (*PaladinContextSourceProvider, error) {
	ev := PaladinContextSourceProvider(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PaladinContextSourceProvider: valid values are %v", v, AllowedPaladinContextSourceProviderEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PaladinContextSourceProvider) IsValid() bool {
	for _, existing := range AllowedPaladinContextSourceProviderEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PaladinContextSourceProvider value
func (v PaladinContextSourceProvider) Ptr() *PaladinContextSourceProvider {
	return &v
}

type NullablePaladinContextSourceProvider struct {
	value *PaladinContextSourceProvider
	isSet bool
}

func (v NullablePaladinContextSourceProvider) Get() *PaladinContextSourceProvider {
	return v.value
}

func (v *NullablePaladinContextSourceProvider) Set(val *PaladinContextSourceProvider) {
	v.value = val
	v.isSet = true
}

func (v NullablePaladinContextSourceProvider) IsSet() bool {
	return v.isSet
}

func (v *NullablePaladinContextSourceProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaladinContextSourceProvider(val *PaladinContextSourceProvider) *NullablePaladinContextSourceProvider {
	return &NullablePaladinContextSourceProvider{value: val, isSet: true}
}

func (v NullablePaladinContextSourceProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaladinContextSourceProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

