/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApproveRequestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApproveRequestRequest{}

// ApproveRequestRequest struct for ApproveRequestRequest
type ApproveRequestRequest struct {
	// The decision level for the approval
	Level string `json:"level"`
	// Optional comment for the approval
	Comment *string `json:"comment,omitempty"`
}

type _ApproveRequestRequest ApproveRequestRequest

// NewApproveRequestRequest instantiates a new ApproveRequestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApproveRequestRequest(level string) *ApproveRequestRequest {
	this := ApproveRequestRequest{}
	this.Level = level
	return &this
}

// NewApproveRequestRequestWithDefaults instantiates a new ApproveRequestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApproveRequestRequestWithDefaults() *ApproveRequestRequest {
	this := ApproveRequestRequest{}
	return &this
}

// GetLevel returns the Level field value
func (o *ApproveRequestRequest) GetLevel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *ApproveRequestRequest) GetLevelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *ApproveRequestRequest) SetLevel(v string) {
	o.Level = v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *ApproveRequestRequest) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApproveRequestRequest) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *ApproveRequestRequest) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *ApproveRequestRequest) SetComment(v string) {
	o.Comment = &v
}

func (o ApproveRequestRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApproveRequestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["level"] = o.Level
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	return toSerialize, nil
}

func (o *ApproveRequestRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"level",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApproveRequestRequest := _ApproveRequestRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApproveRequestRequest)

	if err != nil {
		return err
	}

	*o = ApproveRequestRequest(varApproveRequestRequest)

	return err
}

type NullableApproveRequestRequest struct {
	value *ApproveRequestRequest
	isSet bool
}

func (v NullableApproveRequestRequest) Get() *ApproveRequestRequest {
	return v.value
}

func (v *NullableApproveRequestRequest) Set(val *ApproveRequestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApproveRequestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApproveRequestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApproveRequestRequest(val *ApproveRequestRequest) *NullableApproveRequestRequest {
	return &NullableApproveRequestRequest{value: val, isSet: true}
}

func (v NullableApproveRequestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApproveRequestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


