/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"fmt"
)

// checks if the ResourceRemoteInfoDocusignPermissionProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceRemoteInfoDocusignPermissionProfile{}

// ResourceRemoteInfoDocusignPermissionProfile Remote info for Docusign permission profile.
type ResourceRemoteInfoDocusignPermissionProfile struct {
	// The ID of the Docusign permission profile.
	PermissionProfileId string `json:"permission_profile_id"`
	AdditionalProperties map[string]interface{}
}

type _ResourceRemoteInfoDocusignPermissionProfile ResourceRemoteInfoDocusignPermissionProfile

// NewResourceRemoteInfoDocusignPermissionProfile instantiates a new ResourceRemoteInfoDocusignPermissionProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceRemoteInfoDocusignPermissionProfile(permissionProfileId string) *ResourceRemoteInfoDocusignPermissionProfile {
	this := ResourceRemoteInfoDocusignPermissionProfile{}
	this.PermissionProfileId = permissionProfileId
	return &this
}

// NewResourceRemoteInfoDocusignPermissionProfileWithDefaults instantiates a new ResourceRemoteInfoDocusignPermissionProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceRemoteInfoDocusignPermissionProfileWithDefaults() *ResourceRemoteInfoDocusignPermissionProfile {
	this := ResourceRemoteInfoDocusignPermissionProfile{}
	return &this
}

// GetPermissionProfileId returns the PermissionProfileId field value
func (o *ResourceRemoteInfoDocusignPermissionProfile) GetPermissionProfileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PermissionProfileId
}

// GetPermissionProfileIdOk returns a tuple with the PermissionProfileId field value
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfoDocusignPermissionProfile) GetPermissionProfileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PermissionProfileId, true
}

// SetPermissionProfileId sets field value
func (o *ResourceRemoteInfoDocusignPermissionProfile) SetPermissionProfileId(v string) {
	o.PermissionProfileId = v
}

func (o ResourceRemoteInfoDocusignPermissionProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceRemoteInfoDocusignPermissionProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["permission_profile_id"] = o.PermissionProfileId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResourceRemoteInfoDocusignPermissionProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"permission_profile_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourceRemoteInfoDocusignPermissionProfile := _ResourceRemoteInfoDocusignPermissionProfile{}

	err = json.Unmarshal(data, &varResourceRemoteInfoDocusignPermissionProfile)

	if err != nil {
		return err
	}

	*o = ResourceRemoteInfoDocusignPermissionProfile(varResourceRemoteInfoDocusignPermissionProfile)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "permission_profile_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResourceRemoteInfoDocusignPermissionProfile struct {
	value *ResourceRemoteInfoDocusignPermissionProfile
	isSet bool
}

func (v NullableResourceRemoteInfoDocusignPermissionProfile) Get() *ResourceRemoteInfoDocusignPermissionProfile {
	return v.value
}

func (v *NullableResourceRemoteInfoDocusignPermissionProfile) Set(val *ResourceRemoteInfoDocusignPermissionProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceRemoteInfoDocusignPermissionProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceRemoteInfoDocusignPermissionProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceRemoteInfoDocusignPermissionProfile(val *ResourceRemoteInfoDocusignPermissionProfile) *NullableResourceRemoteInfoDocusignPermissionProfile {
	return &NullableResourceRemoteInfoDocusignPermissionProfile{value: val, isSet: true}
}

func (v NullableResourceRemoteInfoDocusignPermissionProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceRemoteInfoDocusignPermissionProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


