/*
Opal API

Your Home For Developer Resources.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
)

// ResourceRemoteInfo Remote info that is required for the creation of remote resources. Providing this will allow you to omit deprecated remote_id and metadata fields.
type ResourceRemoteInfo struct {
	AwsIamRole *ResourceRemoteInfoAwsIamRole `json:"aws_iam_role,omitempty"`
	AwsEc2Instance *ResourceRemoteInfoAwsEc2Instance `json:"aws_ec2_instance,omitempty"`
	AwsRdsInstance *ResourceRemoteInfoAwsRdsInstance `json:"aws_rds_instance,omitempty"`
	AwsEksCluster *ResourceRemoteInfoAwsEksCluster `json:"aws_eks_cluster,omitempty"`
	GithubRepo *ResourceRemoteInfoGithubRepo `json:"github_repo,omitempty"`
	OktaApp *ResourceRemoteInfoOktaApp `json:"okta_app,omitempty"`
	OktaStandardRole *ResourceRemoteInfoOktaStandardRole `json:"okta_standard_role,omitempty"`
	OktaCustomRole *ResourceRemoteInfoOktaCustomRole `json:"okta_custom_role,omitempty"`
}

// NewResourceRemoteInfo instantiates a new ResourceRemoteInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceRemoteInfo() *ResourceRemoteInfo {
	this := ResourceRemoteInfo{}
	return &this
}

// NewResourceRemoteInfoWithDefaults instantiates a new ResourceRemoteInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceRemoteInfoWithDefaults() *ResourceRemoteInfo {
	this := ResourceRemoteInfo{}
	return &this
}

// GetAwsIamRole returns the AwsIamRole field value if set, zero value otherwise.
func (o *ResourceRemoteInfo) GetAwsIamRole() ResourceRemoteInfoAwsIamRole {
	if o == nil || isNil(o.AwsIamRole) {
		var ret ResourceRemoteInfoAwsIamRole
		return ret
	}
	return *o.AwsIamRole
}

// GetAwsIamRoleOk returns a tuple with the AwsIamRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfo) GetAwsIamRoleOk() (*ResourceRemoteInfoAwsIamRole, bool) {
	if o == nil || isNil(o.AwsIamRole) {
    return nil, false
	}
	return o.AwsIamRole, true
}

// HasAwsIamRole returns a boolean if a field has been set.
func (o *ResourceRemoteInfo) HasAwsIamRole() bool {
	if o != nil && !isNil(o.AwsIamRole) {
		return true
	}

	return false
}

// SetAwsIamRole gets a reference to the given ResourceRemoteInfoAwsIamRole and assigns it to the AwsIamRole field.
func (o *ResourceRemoteInfo) SetAwsIamRole(v ResourceRemoteInfoAwsIamRole) {
	o.AwsIamRole = &v
}

// GetAwsEc2Instance returns the AwsEc2Instance field value if set, zero value otherwise.
func (o *ResourceRemoteInfo) GetAwsEc2Instance() ResourceRemoteInfoAwsEc2Instance {
	if o == nil || isNil(o.AwsEc2Instance) {
		var ret ResourceRemoteInfoAwsEc2Instance
		return ret
	}
	return *o.AwsEc2Instance
}

// GetAwsEc2InstanceOk returns a tuple with the AwsEc2Instance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfo) GetAwsEc2InstanceOk() (*ResourceRemoteInfoAwsEc2Instance, bool) {
	if o == nil || isNil(o.AwsEc2Instance) {
    return nil, false
	}
	return o.AwsEc2Instance, true
}

// HasAwsEc2Instance returns a boolean if a field has been set.
func (o *ResourceRemoteInfo) HasAwsEc2Instance() bool {
	if o != nil && !isNil(o.AwsEc2Instance) {
		return true
	}

	return false
}

// SetAwsEc2Instance gets a reference to the given ResourceRemoteInfoAwsEc2Instance and assigns it to the AwsEc2Instance field.
func (o *ResourceRemoteInfo) SetAwsEc2Instance(v ResourceRemoteInfoAwsEc2Instance) {
	o.AwsEc2Instance = &v
}

// GetAwsRdsInstance returns the AwsRdsInstance field value if set, zero value otherwise.
func (o *ResourceRemoteInfo) GetAwsRdsInstance() ResourceRemoteInfoAwsRdsInstance {
	if o == nil || isNil(o.AwsRdsInstance) {
		var ret ResourceRemoteInfoAwsRdsInstance
		return ret
	}
	return *o.AwsRdsInstance
}

// GetAwsRdsInstanceOk returns a tuple with the AwsRdsInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfo) GetAwsRdsInstanceOk() (*ResourceRemoteInfoAwsRdsInstance, bool) {
	if o == nil || isNil(o.AwsRdsInstance) {
    return nil, false
	}
	return o.AwsRdsInstance, true
}

// HasAwsRdsInstance returns a boolean if a field has been set.
func (o *ResourceRemoteInfo) HasAwsRdsInstance() bool {
	if o != nil && !isNil(o.AwsRdsInstance) {
		return true
	}

	return false
}

// SetAwsRdsInstance gets a reference to the given ResourceRemoteInfoAwsRdsInstance and assigns it to the AwsRdsInstance field.
func (o *ResourceRemoteInfo) SetAwsRdsInstance(v ResourceRemoteInfoAwsRdsInstance) {
	o.AwsRdsInstance = &v
}

// GetAwsEksCluster returns the AwsEksCluster field value if set, zero value otherwise.
func (o *ResourceRemoteInfo) GetAwsEksCluster() ResourceRemoteInfoAwsEksCluster {
	if o == nil || isNil(o.AwsEksCluster) {
		var ret ResourceRemoteInfoAwsEksCluster
		return ret
	}
	return *o.AwsEksCluster
}

// GetAwsEksClusterOk returns a tuple with the AwsEksCluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfo) GetAwsEksClusterOk() (*ResourceRemoteInfoAwsEksCluster, bool) {
	if o == nil || isNil(o.AwsEksCluster) {
    return nil, false
	}
	return o.AwsEksCluster, true
}

// HasAwsEksCluster returns a boolean if a field has been set.
func (o *ResourceRemoteInfo) HasAwsEksCluster() bool {
	if o != nil && !isNil(o.AwsEksCluster) {
		return true
	}

	return false
}

// SetAwsEksCluster gets a reference to the given ResourceRemoteInfoAwsEksCluster and assigns it to the AwsEksCluster field.
func (o *ResourceRemoteInfo) SetAwsEksCluster(v ResourceRemoteInfoAwsEksCluster) {
	o.AwsEksCluster = &v
}

// GetGithubRepo returns the GithubRepo field value if set, zero value otherwise.
func (o *ResourceRemoteInfo) GetGithubRepo() ResourceRemoteInfoGithubRepo {
	if o == nil || isNil(o.GithubRepo) {
		var ret ResourceRemoteInfoGithubRepo
		return ret
	}
	return *o.GithubRepo
}

// GetGithubRepoOk returns a tuple with the GithubRepo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfo) GetGithubRepoOk() (*ResourceRemoteInfoGithubRepo, bool) {
	if o == nil || isNil(o.GithubRepo) {
    return nil, false
	}
	return o.GithubRepo, true
}

// HasGithubRepo returns a boolean if a field has been set.
func (o *ResourceRemoteInfo) HasGithubRepo() bool {
	if o != nil && !isNil(o.GithubRepo) {
		return true
	}

	return false
}

// SetGithubRepo gets a reference to the given ResourceRemoteInfoGithubRepo and assigns it to the GithubRepo field.
func (o *ResourceRemoteInfo) SetGithubRepo(v ResourceRemoteInfoGithubRepo) {
	o.GithubRepo = &v
}

// GetOktaApp returns the OktaApp field value if set, zero value otherwise.
func (o *ResourceRemoteInfo) GetOktaApp() ResourceRemoteInfoOktaApp {
	if o == nil || isNil(o.OktaApp) {
		var ret ResourceRemoteInfoOktaApp
		return ret
	}
	return *o.OktaApp
}

// GetOktaAppOk returns a tuple with the OktaApp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfo) GetOktaAppOk() (*ResourceRemoteInfoOktaApp, bool) {
	if o == nil || isNil(o.OktaApp) {
    return nil, false
	}
	return o.OktaApp, true
}

// HasOktaApp returns a boolean if a field has been set.
func (o *ResourceRemoteInfo) HasOktaApp() bool {
	if o != nil && !isNil(o.OktaApp) {
		return true
	}

	return false
}

// SetOktaApp gets a reference to the given ResourceRemoteInfoOktaApp and assigns it to the OktaApp field.
func (o *ResourceRemoteInfo) SetOktaApp(v ResourceRemoteInfoOktaApp) {
	o.OktaApp = &v
}

// GetOktaStandardRole returns the OktaStandardRole field value if set, zero value otherwise.
func (o *ResourceRemoteInfo) GetOktaStandardRole() ResourceRemoteInfoOktaStandardRole {
	if o == nil || isNil(o.OktaStandardRole) {
		var ret ResourceRemoteInfoOktaStandardRole
		return ret
	}
	return *o.OktaStandardRole
}

// GetOktaStandardRoleOk returns a tuple with the OktaStandardRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfo) GetOktaStandardRoleOk() (*ResourceRemoteInfoOktaStandardRole, bool) {
	if o == nil || isNil(o.OktaStandardRole) {
    return nil, false
	}
	return o.OktaStandardRole, true
}

// HasOktaStandardRole returns a boolean if a field has been set.
func (o *ResourceRemoteInfo) HasOktaStandardRole() bool {
	if o != nil && !isNil(o.OktaStandardRole) {
		return true
	}

	return false
}

// SetOktaStandardRole gets a reference to the given ResourceRemoteInfoOktaStandardRole and assigns it to the OktaStandardRole field.
func (o *ResourceRemoteInfo) SetOktaStandardRole(v ResourceRemoteInfoOktaStandardRole) {
	o.OktaStandardRole = &v
}

// GetOktaCustomRole returns the OktaCustomRole field value if set, zero value otherwise.
func (o *ResourceRemoteInfo) GetOktaCustomRole() ResourceRemoteInfoOktaCustomRole {
	if o == nil || isNil(o.OktaCustomRole) {
		var ret ResourceRemoteInfoOktaCustomRole
		return ret
	}
	return *o.OktaCustomRole
}

// GetOktaCustomRoleOk returns a tuple with the OktaCustomRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfo) GetOktaCustomRoleOk() (*ResourceRemoteInfoOktaCustomRole, bool) {
	if o == nil || isNil(o.OktaCustomRole) {
    return nil, false
	}
	return o.OktaCustomRole, true
}

// HasOktaCustomRole returns a boolean if a field has been set.
func (o *ResourceRemoteInfo) HasOktaCustomRole() bool {
	if o != nil && !isNil(o.OktaCustomRole) {
		return true
	}

	return false
}

// SetOktaCustomRole gets a reference to the given ResourceRemoteInfoOktaCustomRole and assigns it to the OktaCustomRole field.
func (o *ResourceRemoteInfo) SetOktaCustomRole(v ResourceRemoteInfoOktaCustomRole) {
	o.OktaCustomRole = &v
}

func (o ResourceRemoteInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AwsIamRole) {
		toSerialize["aws_iam_role"] = o.AwsIamRole
	}
	if !isNil(o.AwsEc2Instance) {
		toSerialize["aws_ec2_instance"] = o.AwsEc2Instance
	}
	if !isNil(o.AwsRdsInstance) {
		toSerialize["aws_rds_instance"] = o.AwsRdsInstance
	}
	if !isNil(o.AwsEksCluster) {
		toSerialize["aws_eks_cluster"] = o.AwsEksCluster
	}
	if !isNil(o.GithubRepo) {
		toSerialize["github_repo"] = o.GithubRepo
	}
	if !isNil(o.OktaApp) {
		toSerialize["okta_app"] = o.OktaApp
	}
	if !isNil(o.OktaStandardRole) {
		toSerialize["okta_standard_role"] = o.OktaStandardRole
	}
	if !isNil(o.OktaCustomRole) {
		toSerialize["okta_custom_role"] = o.OktaCustomRole
	}
	return json.Marshal(toSerialize)
}

type NullableResourceRemoteInfo struct {
	value *ResourceRemoteInfo
	isSet bool
}

func (v NullableResourceRemoteInfo) Get() *ResourceRemoteInfo {
	return v.value
}

func (v *NullableResourceRemoteInfo) Set(val *ResourceRemoteInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceRemoteInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceRemoteInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceRemoteInfo(val *ResourceRemoteInfo) *NullableResourceRemoteInfo {
	return &NullableResourceRemoteInfo{value: val, isSet: true}
}

func (v NullableResourceRemoteInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceRemoteInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


