/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResourceRemoteInfoGithubOrgRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceRemoteInfoGithubOrgRole{}

// ResourceRemoteInfoGithubOrgRole Remote info for GitHub organization role.
type ResourceRemoteInfoGithubOrgRole struct {
	// The id of the role.
	RoleId string `json:"role_id"`
}

type _ResourceRemoteInfoGithubOrgRole ResourceRemoteInfoGithubOrgRole

// NewResourceRemoteInfoGithubOrgRole instantiates a new ResourceRemoteInfoGithubOrgRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceRemoteInfoGithubOrgRole(roleId string) *ResourceRemoteInfoGithubOrgRole {
	this := ResourceRemoteInfoGithubOrgRole{}
	this.RoleId = roleId
	return &this
}

// NewResourceRemoteInfoGithubOrgRoleWithDefaults instantiates a new ResourceRemoteInfoGithubOrgRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceRemoteInfoGithubOrgRoleWithDefaults() *ResourceRemoteInfoGithubOrgRole {
	this := ResourceRemoteInfoGithubOrgRole{}
	return &this
}

// GetRoleId returns the RoleId field value
func (o *ResourceRemoteInfoGithubOrgRole) GetRoleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfoGithubOrgRole) GetRoleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleId, true
}

// SetRoleId sets field value
func (o *ResourceRemoteInfoGithubOrgRole) SetRoleId(v string) {
	o.RoleId = v
}

func (o ResourceRemoteInfoGithubOrgRole) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceRemoteInfoGithubOrgRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role_id"] = o.RoleId
	return toSerialize, nil
}

func (o *ResourceRemoteInfoGithubOrgRole) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourceRemoteInfoGithubOrgRole := _ResourceRemoteInfoGithubOrgRole{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResourceRemoteInfoGithubOrgRole)

	if err != nil {
		return err
	}

	*o = ResourceRemoteInfoGithubOrgRole(varResourceRemoteInfoGithubOrgRole)

	return err
}

type NullableResourceRemoteInfoGithubOrgRole struct {
	value *ResourceRemoteInfoGithubOrgRole
	isSet bool
}

func (v NullableResourceRemoteInfoGithubOrgRole) Get() *ResourceRemoteInfoGithubOrgRole {
	return v.value
}

func (v *NullableResourceRemoteInfoGithubOrgRole) Set(val *ResourceRemoteInfoGithubOrgRole) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceRemoteInfoGithubOrgRole) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceRemoteInfoGithubOrgRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceRemoteInfoGithubOrgRole(val *ResourceRemoteInfoGithubOrgRole) *NullableResourceRemoteInfoGithubOrgRole {
	return &NullableResourceRemoteInfoGithubOrgRole{value: val, isSet: true}
}

func (v NullableResourceRemoteInfoGithubOrgRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceRemoteInfoGithubOrgRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


