/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"fmt"
)

// checks if the ResourceRemoteInfoGithubEnterpriseRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceRemoteInfoGithubEnterpriseRole{}

// ResourceRemoteInfoGithubEnterpriseRole Remote info for GitHub Enterprise role.
type ResourceRemoteInfoGithubEnterpriseRole struct {
	// The id of the role.
	RoleId string `json:"role_id"`
	AdditionalProperties map[string]interface{}
}

type _ResourceRemoteInfoGithubEnterpriseRole ResourceRemoteInfoGithubEnterpriseRole

// NewResourceRemoteInfoGithubEnterpriseRole instantiates a new ResourceRemoteInfoGithubEnterpriseRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceRemoteInfoGithubEnterpriseRole(roleId string) *ResourceRemoteInfoGithubEnterpriseRole {
	this := ResourceRemoteInfoGithubEnterpriseRole{}
	this.RoleId = roleId
	return &this
}

// NewResourceRemoteInfoGithubEnterpriseRoleWithDefaults instantiates a new ResourceRemoteInfoGithubEnterpriseRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceRemoteInfoGithubEnterpriseRoleWithDefaults() *ResourceRemoteInfoGithubEnterpriseRole {
	this := ResourceRemoteInfoGithubEnterpriseRole{}
	return &this
}

// GetRoleId returns the RoleId field value
func (o *ResourceRemoteInfoGithubEnterpriseRole) GetRoleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfoGithubEnterpriseRole) GetRoleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleId, true
}

// SetRoleId sets field value
func (o *ResourceRemoteInfoGithubEnterpriseRole) SetRoleId(v string) {
	o.RoleId = v
}

func (o ResourceRemoteInfoGithubEnterpriseRole) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceRemoteInfoGithubEnterpriseRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role_id"] = o.RoleId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResourceRemoteInfoGithubEnterpriseRole) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourceRemoteInfoGithubEnterpriseRole := _ResourceRemoteInfoGithubEnterpriseRole{}

	err = json.Unmarshal(data, &varResourceRemoteInfoGithubEnterpriseRole)

	if err != nil {
		return err
	}

	*o = ResourceRemoteInfoGithubEnterpriseRole(varResourceRemoteInfoGithubEnterpriseRole)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "role_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResourceRemoteInfoGithubEnterpriseRole struct {
	value *ResourceRemoteInfoGithubEnterpriseRole
	isSet bool
}

func (v NullableResourceRemoteInfoGithubEnterpriseRole) Get() *ResourceRemoteInfoGithubEnterpriseRole {
	return v.value
}

func (v *NullableResourceRemoteInfoGithubEnterpriseRole) Set(val *ResourceRemoteInfoGithubEnterpriseRole) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceRemoteInfoGithubEnterpriseRole) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceRemoteInfoGithubEnterpriseRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceRemoteInfoGithubEnterpriseRole(val *ResourceRemoteInfoGithubEnterpriseRole) *NullableResourceRemoteInfoGithubEnterpriseRole {
	return &NullableResourceRemoteInfoGithubEnterpriseRole{value: val, isSet: true}
}

func (v NullableResourceRemoteInfoGithubEnterpriseRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceRemoteInfoGithubEnterpriseRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


