/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedResourcesList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedResourcesList{}

// PaginatedResourcesList struct for PaginatedResourcesList
type PaginatedResourcesList struct {
	// The cursor with which to continue pagination if additional result pages exist.
	Next *string `json:"next,omitempty"`
	// The cursor used to obtain the current result page.
	Previous *string `json:"previous,omitempty"`
	Results []Resource `json:"results"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedResourcesList PaginatedResourcesList

// NewPaginatedResourcesList instantiates a new PaginatedResourcesList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedResourcesList(results []Resource) *PaginatedResourcesList {
	this := PaginatedResourcesList{}
	this.Results = results
	return &this
}

// NewPaginatedResourcesListWithDefaults instantiates a new PaginatedResourcesList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedResourcesListWithDefaults() *PaginatedResourcesList {
	this := PaginatedResourcesList{}
	return &this
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *PaginatedResourcesList) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedResourcesList) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *PaginatedResourcesList) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *PaginatedResourcesList) SetNext(v string) {
	o.Next = &v
}

// GetPrevious returns the Previous field value if set, zero value otherwise.
func (o *PaginatedResourcesList) GetPrevious() string {
	if o == nil || IsNil(o.Previous) {
		var ret string
		return ret
	}
	return *o.Previous
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedResourcesList) GetPreviousOk() (*string, bool) {
	if o == nil || IsNil(o.Previous) {
		return nil, false
	}
	return o.Previous, true
}

// HasPrevious returns a boolean if a field has been set.
func (o *PaginatedResourcesList) HasPrevious() bool {
	if o != nil && !IsNil(o.Previous) {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given string and assigns it to the Previous field.
func (o *PaginatedResourcesList) SetPrevious(v string) {
	o.Previous = &v
}

// GetResults returns the Results field value
func (o *PaginatedResourcesList) GetResults() []Resource {
	if o == nil {
		var ret []Resource
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaginatedResourcesList) GetResultsOk() ([]Resource, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaginatedResourcesList) SetResults(v []Resource) {
	o.Results = v
}

func (o PaginatedResourcesList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedResourcesList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Previous) {
		toSerialize["previous"] = o.Previous
	}
	toSerialize["results"] = o.Results

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedResourcesList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedResourcesList := _PaginatedResourcesList{}

	err = json.Unmarshal(data, &varPaginatedResourcesList)

	if err != nil {
		return err
	}

	*o = PaginatedResourcesList(varPaginatedResourcesList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "next")
		delete(additionalProperties, "previous")
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedResourcesList struct {
	value *PaginatedResourcesList
	isSet bool
}

func (v NullablePaginatedResourcesList) Get() *PaginatedResourcesList {
	return v.value
}

func (v *NullablePaginatedResourcesList) Set(val *PaginatedResourcesList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedResourcesList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedResourcesList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedResourcesList(val *PaginatedResourcesList) *NullablePaginatedResourcesList {
	return &NullablePaginatedResourcesList{value: val, isSet: true}
}

func (v NullablePaginatedResourcesList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedResourcesList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


