/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateRequestCommentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRequestCommentRequest{}

// CreateRequestCommentRequest struct for CreateRequestCommentRequest
type CreateRequestCommentRequest struct {
	// comment
	Comment string `json:"comment"`
	AdditionalProperties map[string]interface{}
}

type _CreateRequestCommentRequest CreateRequestCommentRequest

// NewCreateRequestCommentRequest instantiates a new CreateRequestCommentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRequestCommentRequest(comment string) *CreateRequestCommentRequest {
	this := CreateRequestCommentRequest{}
	this.Comment = comment
	return &this
}

// NewCreateRequestCommentRequestWithDefaults instantiates a new CreateRequestCommentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRequestCommentRequestWithDefaults() *CreateRequestCommentRequest {
	this := CreateRequestCommentRequest{}
	return &this
}

// GetComment returns the Comment field value
func (o *CreateRequestCommentRequest) GetComment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Comment
}

// GetCommentOk returns a tuple with the Comment field value
// and a boolean to check if the value has been set.
func (o *CreateRequestCommentRequest) GetCommentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Comment, true
}

// SetComment sets field value
func (o *CreateRequestCommentRequest) SetComment(v string) {
	o.Comment = v
}

func (o CreateRequestCommentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRequestCommentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["comment"] = o.Comment

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateRequestCommentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"comment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRequestCommentRequest := _CreateRequestCommentRequest{}

	err = json.Unmarshal(data, &varCreateRequestCommentRequest)

	if err != nil {
		return err
	}

	*o = CreateRequestCommentRequest(varCreateRequestCommentRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "comment")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateRequestCommentRequest struct {
	value *CreateRequestCommentRequest
	isSet bool
}

func (v NullableCreateRequestCommentRequest) Get() *CreateRequestCommentRequest {
	return v.value
}

func (v *NullableCreateRequestCommentRequest) Set(val *CreateRequestCommentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRequestCommentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRequestCommentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRequestCommentRequest(val *CreateRequestCommentRequest) *NullableCreateRequestCommentRequest {
	return &NullableCreateRequestCommentRequest{value: val, isSet: true}
}

func (v NullableCreateRequestCommentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRequestCommentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


