/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"fmt"
)

// checks if the ResourceRemoteInfoGitlabProject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceRemoteInfoGitlabProject{}

// ResourceRemoteInfoGitlabProject Remote info for Gitlab project.
type ResourceRemoteInfoGitlabProject struct {
	// The id of the project.
	ProjectId string `json:"project_id"`
	AdditionalProperties map[string]interface{}
}

type _ResourceRemoteInfoGitlabProject ResourceRemoteInfoGitlabProject

// NewResourceRemoteInfoGitlabProject instantiates a new ResourceRemoteInfoGitlabProject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceRemoteInfoGitlabProject(projectId string) *ResourceRemoteInfoGitlabProject {
	this := ResourceRemoteInfoGitlabProject{}
	this.ProjectId = projectId
	return &this
}

// NewResourceRemoteInfoGitlabProjectWithDefaults instantiates a new ResourceRemoteInfoGitlabProject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceRemoteInfoGitlabProjectWithDefaults() *ResourceRemoteInfoGitlabProject {
	this := ResourceRemoteInfoGitlabProject{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *ResourceRemoteInfoGitlabProject) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfoGitlabProject) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *ResourceRemoteInfoGitlabProject) SetProjectId(v string) {
	o.ProjectId = v
}

func (o ResourceRemoteInfoGitlabProject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceRemoteInfoGitlabProject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResourceRemoteInfoGitlabProject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourceRemoteInfoGitlabProject := _ResourceRemoteInfoGitlabProject{}

	err = json.Unmarshal(data, &varResourceRemoteInfoGitlabProject)

	if err != nil {
		return err
	}

	*o = ResourceRemoteInfoGitlabProject(varResourceRemoteInfoGitlabProject)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "project_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResourceRemoteInfoGitlabProject struct {
	value *ResourceRemoteInfoGitlabProject
	isSet bool
}

func (v NullableResourceRemoteInfoGitlabProject) Get() *ResourceRemoteInfoGitlabProject {
	return v.value
}

func (v *NullableResourceRemoteInfoGitlabProject) Set(val *ResourceRemoteInfoGitlabProject) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceRemoteInfoGitlabProject) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceRemoteInfoGitlabProject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceRemoteInfoGitlabProject(val *ResourceRemoteInfoGitlabProject) *NullableResourceRemoteInfoGitlabProject {
	return &NullableResourceRemoteInfoGitlabProject{value: val, isSet: true}
}

func (v NullableResourceRemoteInfoGitlabProject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceRemoteInfoGitlabProject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


