/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResourceRemoteInfoGcpBigQueryTable type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceRemoteInfoGcpBigQueryTable{}

// ResourceRemoteInfoGcpBigQueryTable Remote info for GCP BigQuery Table.
type ResourceRemoteInfoGcpBigQueryTable struct {
	// The id of the project the table is in.
	ProjectId string `json:"project_id"`
	// The id of the dataset the table is in.
	DatasetId string `json:"dataset_id"`
	// The id of the table.
	TableId string `json:"table_id"`
}

type _ResourceRemoteInfoGcpBigQueryTable ResourceRemoteInfoGcpBigQueryTable

// NewResourceRemoteInfoGcpBigQueryTable instantiates a new ResourceRemoteInfoGcpBigQueryTable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceRemoteInfoGcpBigQueryTable(projectId string, datasetId string, tableId string) *ResourceRemoteInfoGcpBigQueryTable {
	this := ResourceRemoteInfoGcpBigQueryTable{}
	this.ProjectId = projectId
	this.DatasetId = datasetId
	this.TableId = tableId
	return &this
}

// NewResourceRemoteInfoGcpBigQueryTableWithDefaults instantiates a new ResourceRemoteInfoGcpBigQueryTable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceRemoteInfoGcpBigQueryTableWithDefaults() *ResourceRemoteInfoGcpBigQueryTable {
	this := ResourceRemoteInfoGcpBigQueryTable{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *ResourceRemoteInfoGcpBigQueryTable) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfoGcpBigQueryTable) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *ResourceRemoteInfoGcpBigQueryTable) SetProjectId(v string) {
	o.ProjectId = v
}

// GetDatasetId returns the DatasetId field value
func (o *ResourceRemoteInfoGcpBigQueryTable) GetDatasetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DatasetId
}

// GetDatasetIdOk returns a tuple with the DatasetId field value
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfoGcpBigQueryTable) GetDatasetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DatasetId, true
}

// SetDatasetId sets field value
func (o *ResourceRemoteInfoGcpBigQueryTable) SetDatasetId(v string) {
	o.DatasetId = v
}

// GetTableId returns the TableId field value
func (o *ResourceRemoteInfoGcpBigQueryTable) GetTableId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TableId
}

// GetTableIdOk returns a tuple with the TableId field value
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfoGcpBigQueryTable) GetTableIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TableId, true
}

// SetTableId sets field value
func (o *ResourceRemoteInfoGcpBigQueryTable) SetTableId(v string) {
	o.TableId = v
}

func (o ResourceRemoteInfoGcpBigQueryTable) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceRemoteInfoGcpBigQueryTable) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["dataset_id"] = o.DatasetId
	toSerialize["table_id"] = o.TableId
	return toSerialize, nil
}

func (o *ResourceRemoteInfoGcpBigQueryTable) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"dataset_id",
		"table_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourceRemoteInfoGcpBigQueryTable := _ResourceRemoteInfoGcpBigQueryTable{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResourceRemoteInfoGcpBigQueryTable)

	if err != nil {
		return err
	}

	*o = ResourceRemoteInfoGcpBigQueryTable(varResourceRemoteInfoGcpBigQueryTable)

	return err
}

type NullableResourceRemoteInfoGcpBigQueryTable struct {
	value *ResourceRemoteInfoGcpBigQueryTable
	isSet bool
}

func (v NullableResourceRemoteInfoGcpBigQueryTable) Get() *ResourceRemoteInfoGcpBigQueryTable {
	return v.value
}

func (v *NullableResourceRemoteInfoGcpBigQueryTable) Set(val *ResourceRemoteInfoGcpBigQueryTable) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceRemoteInfoGcpBigQueryTable) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceRemoteInfoGcpBigQueryTable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceRemoteInfoGcpBigQueryTable(val *ResourceRemoteInfoGcpBigQueryTable) *NullableResourceRemoteInfoGcpBigQueryTable {
	return &NullableResourceRemoteInfoGcpBigQueryTable{value: val, isSet: true}
}

func (v NullableResourceRemoteInfoGcpBigQueryTable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceRemoteInfoGcpBigQueryTable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


