/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"fmt"
)

// checks if the PaladinContextSourceList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaladinContextSourceList{}

// PaladinContextSourceList # PaladinContextSourceList Object ### Description A list of `PaladinContextSource` objects.
type PaladinContextSourceList struct {
	Results []PaladinContextSource `json:"results"`
	AdditionalProperties map[string]interface{}
}

type _PaladinContextSourceList PaladinContextSourceList

// NewPaladinContextSourceList instantiates a new PaladinContextSourceList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaladinContextSourceList(results []PaladinContextSource) *PaladinContextSourceList {
	this := PaladinContextSourceList{}
	this.Results = results
	return &this
}

// NewPaladinContextSourceListWithDefaults instantiates a new PaladinContextSourceList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaladinContextSourceListWithDefaults() *PaladinContextSourceList {
	this := PaladinContextSourceList{}
	return &this
}

// GetResults returns the Results field value
func (o *PaladinContextSourceList) GetResults() []PaladinContextSource {
	if o == nil {
		var ret []PaladinContextSource
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *PaladinContextSourceList) GetResultsOk() ([]PaladinContextSource, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *PaladinContextSourceList) SetResults(v []PaladinContextSource) {
	o.Results = v
}

func (o PaladinContextSourceList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaladinContextSourceList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["results"] = o.Results

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaladinContextSourceList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaladinContextSourceList := _PaladinContextSourceList{}

	err = json.Unmarshal(data, &varPaladinContextSourceList)

	if err != nil {
		return err
	}

	*o = PaladinContextSourceList(varPaladinContextSourceList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaladinContextSourceList struct {
	value *PaladinContextSourceList
	isSet bool
}

func (v NullablePaladinContextSourceList) Get() *PaladinContextSourceList {
	return v.value
}

func (v *NullablePaladinContextSourceList) Set(val *PaladinContextSourceList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaladinContextSourceList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaladinContextSourceList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaladinContextSourceList(val *PaladinContextSourceList) *NullablePaladinContextSourceList {
	return &NullablePaladinContextSourceList{value: val, isSet: true}
}

func (v NullablePaladinContextSourceList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaladinContextSourceList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


