/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the Campaign type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Campaign{}

// Campaign An access review campaign.
type Campaign struct {
	// The ID of the campaign.
	CampaignId string `json:"campaign_id"`
	// The name of the campaign.
	Name string `json:"name"`
	Status CampaignStatusEnum `json:"status"`
	// Whether this campaign is a recurring schedule template. Templates spawn draft campaigns on schedule rather than being reviewed directly.
	IsTemplate bool `json:"is_template"`
	// The creation time of the campaign.
	CreatedAt time.Time `json:"created_at"`
	// The last updated time of the campaign.
	UpdatedAt time.Time `json:"updated_at"`
	// The ID of the user who created the campaign.
	CreatedByUserId string `json:"created_by_user_id"`
	// The campaign's configuration, if set.
	Configuration *CampaignConfiguration `json:"configuration,omitempty"`
	// The time the campaign was started, if started.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// The ID of the user who started the campaign, if started.
	StartedByUserId *string `json:"started_by_user_id,omitempty"`
	// The time the campaign was manually stopped, if stopped.
	StoppedAt *time.Time `json:"stopped_at,omitempty"`
	// The ID of the user who stopped the campaign, if stopped.
	StoppedByUserId *string `json:"stopped_by_user_id,omitempty"`
	// The time the campaign reached its scheduled end, if ended.
	EndedAt *time.Time `json:"ended_at,omitempty"`
	// The ID of the user who ended the campaign, if ended.
	EndedByUserId *string `json:"ended_by_user_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Campaign Campaign

// NewCampaign instantiates a new Campaign object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaign(campaignId string, name string, status CampaignStatusEnum, isTemplate bool, createdAt time.Time, updatedAt time.Time, createdByUserId string) *Campaign {
	this := Campaign{}
	this.CampaignId = campaignId
	this.Name = name
	this.Status = status
	this.IsTemplate = isTemplate
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.CreatedByUserId = createdByUserId
	return &this
}

// NewCampaignWithDefaults instantiates a new Campaign object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignWithDefaults() *Campaign {
	this := Campaign{}
	return &this
}

// GetCampaignId returns the CampaignId field value
func (o *Campaign) GetCampaignId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CampaignId
}

// GetCampaignIdOk returns a tuple with the CampaignId field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetCampaignIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CampaignId, true
}

// SetCampaignId sets field value
func (o *Campaign) SetCampaignId(v string) {
	o.CampaignId = v
}

// GetName returns the Name field value
func (o *Campaign) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Campaign) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *Campaign) GetStatus() CampaignStatusEnum {
	if o == nil {
		var ret CampaignStatusEnum
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetStatusOk() (*CampaignStatusEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Campaign) SetStatus(v CampaignStatusEnum) {
	o.Status = v
}

// GetIsTemplate returns the IsTemplate field value
func (o *Campaign) GetIsTemplate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsTemplate
}

// GetIsTemplateOk returns a tuple with the IsTemplate field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetIsTemplateOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsTemplate, true
}

// SetIsTemplate sets field value
func (o *Campaign) SetIsTemplate(v bool) {
	o.IsTemplate = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Campaign) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Campaign) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Campaign) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Campaign) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetCreatedByUserId returns the CreatedByUserId field value
func (o *Campaign) GetCreatedByUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedByUserId
}

// GetCreatedByUserIdOk returns a tuple with the CreatedByUserId field value
// and a boolean to check if the value has been set.
func (o *Campaign) GetCreatedByUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedByUserId, true
}

// SetCreatedByUserId sets field value
func (o *Campaign) SetCreatedByUserId(v string) {
	o.CreatedByUserId = v
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
func (o *Campaign) GetConfiguration() CampaignConfiguration {
	if o == nil || IsNil(o.Configuration) {
		var ret CampaignConfiguration
		return ret
	}
	return *o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetConfigurationOk() (*CampaignConfiguration, bool) {
	if o == nil || IsNil(o.Configuration) {
		return nil, false
	}
	return o.Configuration, true
}

// HasConfiguration returns a boolean if a field has been set.
func (o *Campaign) HasConfiguration() bool {
	if o != nil && !IsNil(o.Configuration) {
		return true
	}

	return false
}

// SetConfiguration gets a reference to the given CampaignConfiguration and assigns it to the Configuration field.
func (o *Campaign) SetConfiguration(v CampaignConfiguration) {
	o.Configuration = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *Campaign) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetStartedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *Campaign) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given time.Time and assigns it to the StartedAt field.
func (o *Campaign) SetStartedAt(v time.Time) {
	o.StartedAt = &v
}

// GetStartedByUserId returns the StartedByUserId field value if set, zero value otherwise.
func (o *Campaign) GetStartedByUserId() string {
	if o == nil || IsNil(o.StartedByUserId) {
		var ret string
		return ret
	}
	return *o.StartedByUserId
}

// GetStartedByUserIdOk returns a tuple with the StartedByUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetStartedByUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.StartedByUserId) {
		return nil, false
	}
	return o.StartedByUserId, true
}

// HasStartedByUserId returns a boolean if a field has been set.
func (o *Campaign) HasStartedByUserId() bool {
	if o != nil && !IsNil(o.StartedByUserId) {
		return true
	}

	return false
}

// SetStartedByUserId gets a reference to the given string and assigns it to the StartedByUserId field.
func (o *Campaign) SetStartedByUserId(v string) {
	o.StartedByUserId = &v
}

// GetStoppedAt returns the StoppedAt field value if set, zero value otherwise.
func (o *Campaign) GetStoppedAt() time.Time {
	if o == nil || IsNil(o.StoppedAt) {
		var ret time.Time
		return ret
	}
	return *o.StoppedAt
}

// GetStoppedAtOk returns a tuple with the StoppedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetStoppedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StoppedAt) {
		return nil, false
	}
	return o.StoppedAt, true
}

// HasStoppedAt returns a boolean if a field has been set.
func (o *Campaign) HasStoppedAt() bool {
	if o != nil && !IsNil(o.StoppedAt) {
		return true
	}

	return false
}

// SetStoppedAt gets a reference to the given time.Time and assigns it to the StoppedAt field.
func (o *Campaign) SetStoppedAt(v time.Time) {
	o.StoppedAt = &v
}

// GetStoppedByUserId returns the StoppedByUserId field value if set, zero value otherwise.
func (o *Campaign) GetStoppedByUserId() string {
	if o == nil || IsNil(o.StoppedByUserId) {
		var ret string
		return ret
	}
	return *o.StoppedByUserId
}

// GetStoppedByUserIdOk returns a tuple with the StoppedByUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetStoppedByUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.StoppedByUserId) {
		return nil, false
	}
	return o.StoppedByUserId, true
}

// HasStoppedByUserId returns a boolean if a field has been set.
func (o *Campaign) HasStoppedByUserId() bool {
	if o != nil && !IsNil(o.StoppedByUserId) {
		return true
	}

	return false
}

// SetStoppedByUserId gets a reference to the given string and assigns it to the StoppedByUserId field.
func (o *Campaign) SetStoppedByUserId(v string) {
	o.StoppedByUserId = &v
}

// GetEndedAt returns the EndedAt field value if set, zero value otherwise.
func (o *Campaign) GetEndedAt() time.Time {
	if o == nil || IsNil(o.EndedAt) {
		var ret time.Time
		return ret
	}
	return *o.EndedAt
}

// GetEndedAtOk returns a tuple with the EndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetEndedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndedAt) {
		return nil, false
	}
	return o.EndedAt, true
}

// HasEndedAt returns a boolean if a field has been set.
func (o *Campaign) HasEndedAt() bool {
	if o != nil && !IsNil(o.EndedAt) {
		return true
	}

	return false
}

// SetEndedAt gets a reference to the given time.Time and assigns it to the EndedAt field.
func (o *Campaign) SetEndedAt(v time.Time) {
	o.EndedAt = &v
}

// GetEndedByUserId returns the EndedByUserId field value if set, zero value otherwise.
func (o *Campaign) GetEndedByUserId() string {
	if o == nil || IsNil(o.EndedByUserId) {
		var ret string
		return ret
	}
	return *o.EndedByUserId
}

// GetEndedByUserIdOk returns a tuple with the EndedByUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Campaign) GetEndedByUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.EndedByUserId) {
		return nil, false
	}
	return o.EndedByUserId, true
}

// HasEndedByUserId returns a boolean if a field has been set.
func (o *Campaign) HasEndedByUserId() bool {
	if o != nil && !IsNil(o.EndedByUserId) {
		return true
	}

	return false
}

// SetEndedByUserId gets a reference to the given string and assigns it to the EndedByUserId field.
func (o *Campaign) SetEndedByUserId(v string) {
	o.EndedByUserId = &v
}

func (o Campaign) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Campaign) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["campaign_id"] = o.CampaignId
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	toSerialize["is_template"] = o.IsTemplate
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["created_by_user_id"] = o.CreatedByUserId
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	if !IsNil(o.StartedAt) {
		toSerialize["started_at"] = o.StartedAt
	}
	if !IsNil(o.StartedByUserId) {
		toSerialize["started_by_user_id"] = o.StartedByUserId
	}
	if !IsNil(o.StoppedAt) {
		toSerialize["stopped_at"] = o.StoppedAt
	}
	if !IsNil(o.StoppedByUserId) {
		toSerialize["stopped_by_user_id"] = o.StoppedByUserId
	}
	if !IsNil(o.EndedAt) {
		toSerialize["ended_at"] = o.EndedAt
	}
	if !IsNil(o.EndedByUserId) {
		toSerialize["ended_by_user_id"] = o.EndedByUserId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Campaign) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"campaign_id",
		"name",
		"status",
		"is_template",
		"created_at",
		"updated_at",
		"created_by_user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCampaign := _Campaign{}

	err = json.Unmarshal(data, &varCampaign)

	if err != nil {
		return err
	}

	*o = Campaign(varCampaign)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "campaign_id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "status")
		delete(additionalProperties, "is_template")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "created_by_user_id")
		delete(additionalProperties, "configuration")
		delete(additionalProperties, "started_at")
		delete(additionalProperties, "started_by_user_id")
		delete(additionalProperties, "stopped_at")
		delete(additionalProperties, "stopped_by_user_id")
		delete(additionalProperties, "ended_at")
		delete(additionalProperties, "ended_by_user_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCampaign struct {
	value *Campaign
	isSet bool
}

func (v NullableCampaign) Get() *Campaign {
	return v.value
}

func (v *NullableCampaign) Set(val *Campaign) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaign) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaign) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaign(val *Campaign) *NullableCampaign {
	return &NullableCampaign{value: val, isSet: true}
}

func (v NullableCampaign) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaign) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


