/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupRemoteInfoDatabricksAccountGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupRemoteInfoDatabricksAccountGroup{}

// GroupRemoteInfoDatabricksAccountGroup Remote info for Databricks account group.
type GroupRemoteInfoDatabricksAccountGroup struct {
	// The id of the Databricks account group.
	GroupId string `json:"group_id"`
}

type _GroupRemoteInfoDatabricksAccountGroup GroupRemoteInfoDatabricksAccountGroup

// NewGroupRemoteInfoDatabricksAccountGroup instantiates a new GroupRemoteInfoDatabricksAccountGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupRemoteInfoDatabricksAccountGroup(groupId string) *GroupRemoteInfoDatabricksAccountGroup {
	this := GroupRemoteInfoDatabricksAccountGroup{}
	this.GroupId = groupId
	return &this
}

// NewGroupRemoteInfoDatabricksAccountGroupWithDefaults instantiates a new GroupRemoteInfoDatabricksAccountGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupRemoteInfoDatabricksAccountGroupWithDefaults() *GroupRemoteInfoDatabricksAccountGroup {
	this := GroupRemoteInfoDatabricksAccountGroup{}
	return &this
}

// GetGroupId returns the GroupId field value
func (o *GroupRemoteInfoDatabricksAccountGroup) GetGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value
// and a boolean to check if the value has been set.
func (o *GroupRemoteInfoDatabricksAccountGroup) GetGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupId, true
}

// SetGroupId sets field value
func (o *GroupRemoteInfoDatabricksAccountGroup) SetGroupId(v string) {
	o.GroupId = v
}

func (o GroupRemoteInfoDatabricksAccountGroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupRemoteInfoDatabricksAccountGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["group_id"] = o.GroupId
	return toSerialize, nil
}

func (o *GroupRemoteInfoDatabricksAccountGroup) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"group_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupRemoteInfoDatabricksAccountGroup := _GroupRemoteInfoDatabricksAccountGroup{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupRemoteInfoDatabricksAccountGroup)

	if err != nil {
		return err
	}

	*o = GroupRemoteInfoDatabricksAccountGroup(varGroupRemoteInfoDatabricksAccountGroup)

	return err
}

type NullableGroupRemoteInfoDatabricksAccountGroup struct {
	value *GroupRemoteInfoDatabricksAccountGroup
	isSet bool
}

func (v NullableGroupRemoteInfoDatabricksAccountGroup) Get() *GroupRemoteInfoDatabricksAccountGroup {
	return v.value
}

func (v *NullableGroupRemoteInfoDatabricksAccountGroup) Set(val *GroupRemoteInfoDatabricksAccountGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupRemoteInfoDatabricksAccountGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupRemoteInfoDatabricksAccountGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupRemoteInfoDatabricksAccountGroup(val *GroupRemoteInfoDatabricksAccountGroup) *NullableGroupRemoteInfoDatabricksAccountGroup {
	return &NullableGroupRemoteInfoDatabricksAccountGroup{value: val, isSet: true}
}

func (v NullableGroupRemoteInfoDatabricksAccountGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupRemoteInfoDatabricksAccountGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


