/*
Opal API

Your Home For Developer Resources.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
)

// checks if the MessageChannelList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageChannelList{}

// MessageChannelList struct for MessageChannelList
type MessageChannelList struct {
	Channels []MessageChannel `json:"channels"`
}

// NewMessageChannelList instantiates a new MessageChannelList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageChannelList(channels []MessageChannel) *MessageChannelList {
	this := MessageChannelList{}
	this.Channels = channels
	return &this
}

// NewMessageChannelListWithDefaults instantiates a new MessageChannelList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageChannelListWithDefaults() *MessageChannelList {
	this := MessageChannelList{}
	return &this
}

// GetChannels returns the Channels field value
func (o *MessageChannelList) GetChannels() []MessageChannel {
	if o == nil {
		var ret []MessageChannel
		return ret
	}

	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value
// and a boolean to check if the value has been set.
func (o *MessageChannelList) GetChannelsOk() ([]MessageChannel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Channels, true
}

// SetChannels sets field value
func (o *MessageChannelList) SetChannels(v []MessageChannel) {
	o.Channels = v
}

func (o MessageChannelList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageChannelList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channels"] = o.Channels
	return toSerialize, nil
}

type NullableMessageChannelList struct {
	value *MessageChannelList
	isSet bool
}

func (v NullableMessageChannelList) Get() *MessageChannelList {
	return v.value
}

func (v *NullableMessageChannelList) Set(val *MessageChannelList) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageChannelList) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageChannelList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageChannelList(val *MessageChannelList) *NullableMessageChannelList {
	return &NullableMessageChannelList{value: val, isSet: true}
}

func (v NullableMessageChannelList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageChannelList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


