/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"fmt"
)

// checks if the ResourceRemoteInfoDevinOrganization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceRemoteInfoDevinOrganization{}

// ResourceRemoteInfoDevinOrganization Remote info for Devin organization.
type ResourceRemoteInfoDevinOrganization struct {
	// The id of the organization.
	OrgId string `json:"org_id"`
	AdditionalProperties map[string]interface{}
}

type _ResourceRemoteInfoDevinOrganization ResourceRemoteInfoDevinOrganization

// NewResourceRemoteInfoDevinOrganization instantiates a new ResourceRemoteInfoDevinOrganization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceRemoteInfoDevinOrganization(orgId string) *ResourceRemoteInfoDevinOrganization {
	this := ResourceRemoteInfoDevinOrganization{}
	this.OrgId = orgId
	return &this
}

// NewResourceRemoteInfoDevinOrganizationWithDefaults instantiates a new ResourceRemoteInfoDevinOrganization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceRemoteInfoDevinOrganizationWithDefaults() *ResourceRemoteInfoDevinOrganization {
	this := ResourceRemoteInfoDevinOrganization{}
	return &this
}

// GetOrgId returns the OrgId field value
func (o *ResourceRemoteInfoDevinOrganization) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfoDevinOrganization) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *ResourceRemoteInfoDevinOrganization) SetOrgId(v string) {
	o.OrgId = v
}

func (o ResourceRemoteInfoDevinOrganization) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceRemoteInfoDevinOrganization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["org_id"] = o.OrgId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResourceRemoteInfoDevinOrganization) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"org_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourceRemoteInfoDevinOrganization := _ResourceRemoteInfoDevinOrganization{}

	err = json.Unmarshal(data, &varResourceRemoteInfoDevinOrganization)

	if err != nil {
		return err
	}

	*o = ResourceRemoteInfoDevinOrganization(varResourceRemoteInfoDevinOrganization)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "org_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResourceRemoteInfoDevinOrganization struct {
	value *ResourceRemoteInfoDevinOrganization
	isSet bool
}

func (v NullableResourceRemoteInfoDevinOrganization) Get() *ResourceRemoteInfoDevinOrganization {
	return v.value
}

func (v *NullableResourceRemoteInfoDevinOrganization) Set(val *ResourceRemoteInfoDevinOrganization) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceRemoteInfoDevinOrganization) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceRemoteInfoDevinOrganization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceRemoteInfoDevinOrganization(val *ResourceRemoteInfoDevinOrganization) *NullableResourceRemoteInfoDevinOrganization {
	return &NullableResourceRemoteInfoDevinOrganization{value: val, isSet: true}
}

func (v NullableResourceRemoteInfoDevinOrganization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceRemoteInfoDevinOrganization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


