/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResourceRemoteInfoAzureStorageContainer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceRemoteInfoAzureStorageContainer{}

// ResourceRemoteInfoAzureStorageContainer Remote info for Azure storage container.
type ResourceRemoteInfoAzureStorageContainer struct {
	// The ARM resource ID of the storage container.
	ResourceId string `json:"resource_id"`
}

type _ResourceRemoteInfoAzureStorageContainer ResourceRemoteInfoAzureStorageContainer

// NewResourceRemoteInfoAzureStorageContainer instantiates a new ResourceRemoteInfoAzureStorageContainer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceRemoteInfoAzureStorageContainer(resourceId string) *ResourceRemoteInfoAzureStorageContainer {
	this := ResourceRemoteInfoAzureStorageContainer{}
	this.ResourceId = resourceId
	return &this
}

// NewResourceRemoteInfoAzureStorageContainerWithDefaults instantiates a new ResourceRemoteInfoAzureStorageContainer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceRemoteInfoAzureStorageContainerWithDefaults() *ResourceRemoteInfoAzureStorageContainer {
	this := ResourceRemoteInfoAzureStorageContainer{}
	return &this
}

// GetResourceId returns the ResourceId field value
func (o *ResourceRemoteInfoAzureStorageContainer) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfoAzureStorageContainer) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *ResourceRemoteInfoAzureStorageContainer) SetResourceId(v string) {
	o.ResourceId = v
}

func (o ResourceRemoteInfoAzureStorageContainer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceRemoteInfoAzureStorageContainer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resource_id"] = o.ResourceId
	return toSerialize, nil
}

func (o *ResourceRemoteInfoAzureStorageContainer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resource_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourceRemoteInfoAzureStorageContainer := _ResourceRemoteInfoAzureStorageContainer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResourceRemoteInfoAzureStorageContainer)

	if err != nil {
		return err
	}

	*o = ResourceRemoteInfoAzureStorageContainer(varResourceRemoteInfoAzureStorageContainer)

	return err
}

type NullableResourceRemoteInfoAzureStorageContainer struct {
	value *ResourceRemoteInfoAzureStorageContainer
	isSet bool
}

func (v NullableResourceRemoteInfoAzureStorageContainer) Get() *ResourceRemoteInfoAzureStorageContainer {
	return v.value
}

func (v *NullableResourceRemoteInfoAzureStorageContainer) Set(val *ResourceRemoteInfoAzureStorageContainer) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceRemoteInfoAzureStorageContainer) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceRemoteInfoAzureStorageContainer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceRemoteInfoAzureStorageContainer(val *ResourceRemoteInfoAzureStorageContainer) *NullableResourceRemoteInfoAzureStorageContainer {
	return &NullableResourceRemoteInfoAzureStorageContainer{value: val, isSet: true}
}

func (v NullableResourceRemoteInfoAzureStorageContainer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceRemoteInfoAzureStorageContainer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


