/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"fmt"
)

// checks if the ResourceRemoteInfoAzureUserAssignedManagedIdentity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceRemoteInfoAzureUserAssignedManagedIdentity{}

// ResourceRemoteInfoAzureUserAssignedManagedIdentity Remote info for Azure user assigned managed identity.
type ResourceRemoteInfoAzureUserAssignedManagedIdentity struct {
	// The ARM resource ID of the user assigned managed identity.
	ResourceId string `json:"resource_id"`
	AdditionalProperties map[string]interface{}
}

type _ResourceRemoteInfoAzureUserAssignedManagedIdentity ResourceRemoteInfoAzureUserAssignedManagedIdentity

// NewResourceRemoteInfoAzureUserAssignedManagedIdentity instantiates a new ResourceRemoteInfoAzureUserAssignedManagedIdentity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceRemoteInfoAzureUserAssignedManagedIdentity(resourceId string) *ResourceRemoteInfoAzureUserAssignedManagedIdentity {
	this := ResourceRemoteInfoAzureUserAssignedManagedIdentity{}
	this.ResourceId = resourceId
	return &this
}

// NewResourceRemoteInfoAzureUserAssignedManagedIdentityWithDefaults instantiates a new ResourceRemoteInfoAzureUserAssignedManagedIdentity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceRemoteInfoAzureUserAssignedManagedIdentityWithDefaults() *ResourceRemoteInfoAzureUserAssignedManagedIdentity {
	this := ResourceRemoteInfoAzureUserAssignedManagedIdentity{}
	return &this
}

// GetResourceId returns the ResourceId field value
func (o *ResourceRemoteInfoAzureUserAssignedManagedIdentity) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfoAzureUserAssignedManagedIdentity) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *ResourceRemoteInfoAzureUserAssignedManagedIdentity) SetResourceId(v string) {
	o.ResourceId = v
}

func (o ResourceRemoteInfoAzureUserAssignedManagedIdentity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceRemoteInfoAzureUserAssignedManagedIdentity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resource_id"] = o.ResourceId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ResourceRemoteInfoAzureUserAssignedManagedIdentity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resource_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourceRemoteInfoAzureUserAssignedManagedIdentity := _ResourceRemoteInfoAzureUserAssignedManagedIdentity{}

	err = json.Unmarshal(data, &varResourceRemoteInfoAzureUserAssignedManagedIdentity)

	if err != nil {
		return err
	}

	*o = ResourceRemoteInfoAzureUserAssignedManagedIdentity(varResourceRemoteInfoAzureUserAssignedManagedIdentity)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "resource_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableResourceRemoteInfoAzureUserAssignedManagedIdentity struct {
	value *ResourceRemoteInfoAzureUserAssignedManagedIdentity
	isSet bool
}

func (v NullableResourceRemoteInfoAzureUserAssignedManagedIdentity) Get() *ResourceRemoteInfoAzureUserAssignedManagedIdentity {
	return v.value
}

func (v *NullableResourceRemoteInfoAzureUserAssignedManagedIdentity) Set(val *ResourceRemoteInfoAzureUserAssignedManagedIdentity) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceRemoteInfoAzureUserAssignedManagedIdentity) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceRemoteInfoAzureUserAssignedManagedIdentity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceRemoteInfoAzureUserAssignedManagedIdentity(val *ResourceRemoteInfoAzureUserAssignedManagedIdentity) *NullableResourceRemoteInfoAzureUserAssignedManagedIdentity {
	return &NullableResourceRemoteInfoAzureUserAssignedManagedIdentity{value: val, isSet: true}
}

func (v NullableResourceRemoteInfoAzureUserAssignedManagedIdentity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceRemoteInfoAzureUserAssignedManagedIdentity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


