/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"fmt"
)

// checks if the RequestTemplateCustomField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestTemplateCustomField{}

// RequestTemplateCustomField A field on a request template.
type RequestTemplateCustomField struct {
	// The label shown to the requester. `CALLOUT` fields are display-only, so their name is an internal identifier and is never displayed.
	Name string `json:"name"`
	// Helper text shown beneath the field.
	Description *string `json:"description,omitempty"`
	Type RequestTemplateCustomFieldTypeEnum `json:"type"`
	// Whether the requester must answer. Always false for `CALLOUT` fields, which collect no answer.
	Required *bool `json:"required,omitempty"`
	Metadata *RequestTemplateCustomFieldMetadata `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RequestTemplateCustomField RequestTemplateCustomField

// NewRequestTemplateCustomField instantiates a new RequestTemplateCustomField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestTemplateCustomField(name string, type_ RequestTemplateCustomFieldTypeEnum) *RequestTemplateCustomField {
	this := RequestTemplateCustomField{}
	this.Name = name
	this.Type = type_
	return &this
}

// NewRequestTemplateCustomFieldWithDefaults instantiates a new RequestTemplateCustomField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestTemplateCustomFieldWithDefaults() *RequestTemplateCustomField {
	this := RequestTemplateCustomField{}
	return &this
}

// GetName returns the Name field value
func (o *RequestTemplateCustomField) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RequestTemplateCustomField) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RequestTemplateCustomField) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RequestTemplateCustomField) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestTemplateCustomField) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RequestTemplateCustomField) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RequestTemplateCustomField) SetDescription(v string) {
	o.Description = &v
}

// GetType returns the Type field value
func (o *RequestTemplateCustomField) GetType() RequestTemplateCustomFieldTypeEnum {
	if o == nil {
		var ret RequestTemplateCustomFieldTypeEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RequestTemplateCustomField) GetTypeOk() (*RequestTemplateCustomFieldTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RequestTemplateCustomField) SetType(v RequestTemplateCustomFieldTypeEnum) {
	o.Type = v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *RequestTemplateCustomField) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestTemplateCustomField) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *RequestTemplateCustomField) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *RequestTemplateCustomField) SetRequired(v bool) {
	o.Required = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *RequestTemplateCustomField) GetMetadata() RequestTemplateCustomFieldMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret RequestTemplateCustomFieldMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestTemplateCustomField) GetMetadataOk() (*RequestTemplateCustomFieldMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *RequestTemplateCustomField) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given RequestTemplateCustomFieldMetadata and assigns it to the Metadata field.
func (o *RequestTemplateCustomField) SetMetadata(v RequestTemplateCustomFieldMetadata) {
	o.Metadata = &v
}

func (o RequestTemplateCustomField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestTemplateCustomField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RequestTemplateCustomField) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRequestTemplateCustomField := _RequestTemplateCustomField{}

	err = json.Unmarshal(data, &varRequestTemplateCustomField)

	if err != nil {
		return err
	}

	*o = RequestTemplateCustomField(varRequestTemplateCustomField)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "type")
		delete(additionalProperties, "required")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRequestTemplateCustomField struct {
	value *RequestTemplateCustomField
	isSet bool
}

func (v NullableRequestTemplateCustomField) Get() *RequestTemplateCustomField {
	return v.value
}

func (v *NullableRequestTemplateCustomField) Set(val *RequestTemplateCustomField) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestTemplateCustomField) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestTemplateCustomField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestTemplateCustomField(val *RequestTemplateCustomField) *NullableRequestTemplateCustomField {
	return &NullableRequestTemplateCustomField{value: val, isSet: true}
}

func (v NullableRequestTemplateCustomField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestTemplateCustomField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


