/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"fmt"
)

// RDSEngineEnum The database engine for the RDS instance.
type RDSEngineEnum string

// List of RDSEngineEnum
const (
	RDSENGINEENUM_MYSQL RDSEngineEnum = "MYSQL"
	RDSENGINEENUM_POSTGRESQL RDSEngineEnum = "POSTGRESQL"
)

// All allowed values of RDSEngineEnum enum
var AllowedRDSEngineEnumEnumValues = []RDSEngineEnum{
	"MYSQL",
	"POSTGRESQL",
}

func (v *RDSEngineEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RDSEngineEnum(value)
	for _, existing := range AllowedRDSEngineEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RDSEngineEnum", value)
}

// NewRDSEngineEnumFromValue returns a pointer to a valid RDSEngineEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRDSEngineEnumFromValue(v string) (*RDSEngineEnum, error) {
	ev := RDSEngineEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RDSEngineEnum: valid values are %v", v, AllowedRDSEngineEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RDSEngineEnum) IsValid() bool {
	for _, existing := range AllowedRDSEngineEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RDSEngineEnum value
func (v RDSEngineEnum) Ptr() *RDSEngineEnum {
	return &v
}

type NullableRDSEngineEnum struct {
	value *RDSEngineEnum
	isSet bool
}

func (v NullableRDSEngineEnum) Get() *RDSEngineEnum {
	return v.value
}

func (v *NullableRDSEngineEnum) Set(val *RDSEngineEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableRDSEngineEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableRDSEngineEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRDSEngineEnum(val *RDSEngineEnum) *NullableRDSEngineEnum {
	return &NullableRDSEngineEnum{value: val, isSet: true}
}

func (v NullableRDSEngineEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRDSEngineEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

