/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Token type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Token{}

// Token A first-party API token.
type Token struct {
	// The ID of the API token.
	TokenId string `json:"token_id"`
	// The date and time the token was created.
	CreatedAt time.Time `json:"created_at"`
	// A human-readable label for the token.
	TokenLabel string `json:"token_label"`
	// The ID of the user who created the token.
	CreatorUserId string `json:"creator_user_id"`
	// The ID of the user the token authenticates as.
	UserId string `json:"user_id"`
	// The date and time the token was last used.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	AccessLevel ApiAccessLevelEnum `json:"access_level"`
	// The date and time the token expires.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
}

type _Token Token

// NewToken instantiates a new Token object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToken(tokenId string, createdAt time.Time, tokenLabel string, creatorUserId string, userId string, accessLevel ApiAccessLevelEnum) *Token {
	this := Token{}
	this.TokenId = tokenId
	this.CreatedAt = createdAt
	this.TokenLabel = tokenLabel
	this.CreatorUserId = creatorUserId
	this.UserId = userId
	this.AccessLevel = accessLevel
	return &this
}

// NewTokenWithDefaults instantiates a new Token object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenWithDefaults() *Token {
	this := Token{}
	return &this
}

// GetTokenId returns the TokenId field value
func (o *Token) GetTokenId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *Token) GetTokenIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *Token) SetTokenId(v string) {
	o.TokenId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Token) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Token) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Token) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetTokenLabel returns the TokenLabel field value
func (o *Token) GetTokenLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenLabel
}

// GetTokenLabelOk returns a tuple with the TokenLabel field value
// and a boolean to check if the value has been set.
func (o *Token) GetTokenLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenLabel, true
}

// SetTokenLabel sets field value
func (o *Token) SetTokenLabel(v string) {
	o.TokenLabel = v
}

// GetCreatorUserId returns the CreatorUserId field value
func (o *Token) GetCreatorUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatorUserId
}

// GetCreatorUserIdOk returns a tuple with the CreatorUserId field value
// and a boolean to check if the value has been set.
func (o *Token) GetCreatorUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatorUserId, true
}

// SetCreatorUserId sets field value
func (o *Token) SetCreatorUserId(v string) {
	o.CreatorUserId = v
}

// GetUserId returns the UserId field value
func (o *Token) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *Token) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *Token) SetUserId(v string) {
	o.UserId = v
}

// GetLastUsedAt returns the LastUsedAt field value if set, zero value otherwise.
func (o *Token) GetLastUsedAt() time.Time {
	if o == nil || IsNil(o.LastUsedAt) {
		var ret time.Time
		return ret
	}
	return *o.LastUsedAt
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetLastUsedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastUsedAt) {
		return nil, false
	}
	return o.LastUsedAt, true
}

// HasLastUsedAt returns a boolean if a field has been set.
func (o *Token) HasLastUsedAt() bool {
	if o != nil && !IsNil(o.LastUsedAt) {
		return true
	}

	return false
}

// SetLastUsedAt gets a reference to the given time.Time and assigns it to the LastUsedAt field.
func (o *Token) SetLastUsedAt(v time.Time) {
	o.LastUsedAt = &v
}

// GetAccessLevel returns the AccessLevel field value
func (o *Token) GetAccessLevel() ApiAccessLevelEnum {
	if o == nil {
		var ret ApiAccessLevelEnum
		return ret
	}

	return o.AccessLevel
}

// GetAccessLevelOk returns a tuple with the AccessLevel field value
// and a boolean to check if the value has been set.
func (o *Token) GetAccessLevelOk() (*ApiAccessLevelEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessLevel, true
}

// SetAccessLevel sets field value
func (o *Token) SetAccessLevel(v ApiAccessLevelEnum) {
	o.AccessLevel = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *Token) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Token) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *Token) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *Token) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

func (o Token) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Token) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token_id"] = o.TokenId
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["token_label"] = o.TokenLabel
	toSerialize["creator_user_id"] = o.CreatorUserId
	toSerialize["user_id"] = o.UserId
	if !IsNil(o.LastUsedAt) {
		toSerialize["last_used_at"] = o.LastUsedAt
	}
	toSerialize["access_level"] = o.AccessLevel
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	return toSerialize, nil
}

func (o *Token) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token_id",
		"created_at",
		"token_label",
		"creator_user_id",
		"user_id",
		"access_level",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varToken := _Token{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varToken)

	if err != nil {
		return err
	}

	*o = Token(varToken)

	return err
}

type NullableToken struct {
	value *Token
	isSet bool
}

func (v NullableToken) Get() *Token {
	return v.value
}

func (v *NullableToken) Set(val *Token) {
	v.value = val
	v.isSet = true
}

func (v NullableToken) IsSet() bool {
	return v.isSet
}

func (v *NullableToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToken(val *Token) *NullableToken {
	return &NullableToken{value: val, isSet: true}
}

func (v NullableToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


