/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResourceRemoteInfoGithubOrg type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResourceRemoteInfoGithubOrg{}

// ResourceRemoteInfoGithubOrg Remote info for GitHub organization.
type ResourceRemoteInfoGithubOrg struct {
	// The name of the organization.
	OrgName string `json:"org_name"`
}

type _ResourceRemoteInfoGithubOrg ResourceRemoteInfoGithubOrg

// NewResourceRemoteInfoGithubOrg instantiates a new ResourceRemoteInfoGithubOrg object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceRemoteInfoGithubOrg(orgName string) *ResourceRemoteInfoGithubOrg {
	this := ResourceRemoteInfoGithubOrg{}
	this.OrgName = orgName
	return &this
}

// NewResourceRemoteInfoGithubOrgWithDefaults instantiates a new ResourceRemoteInfoGithubOrg object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceRemoteInfoGithubOrgWithDefaults() *ResourceRemoteInfoGithubOrg {
	this := ResourceRemoteInfoGithubOrg{}
	return &this
}

// GetOrgName returns the OrgName field value
func (o *ResourceRemoteInfoGithubOrg) GetOrgName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgName
}

// GetOrgNameOk returns a tuple with the OrgName field value
// and a boolean to check if the value has been set.
func (o *ResourceRemoteInfoGithubOrg) GetOrgNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgName, true
}

// SetOrgName sets field value
func (o *ResourceRemoteInfoGithubOrg) SetOrgName(v string) {
	o.OrgName = v
}

func (o ResourceRemoteInfoGithubOrg) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResourceRemoteInfoGithubOrg) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["org_name"] = o.OrgName
	return toSerialize, nil
}

func (o *ResourceRemoteInfoGithubOrg) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"org_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResourceRemoteInfoGithubOrg := _ResourceRemoteInfoGithubOrg{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResourceRemoteInfoGithubOrg)

	if err != nil {
		return err
	}

	*o = ResourceRemoteInfoGithubOrg(varResourceRemoteInfoGithubOrg)

	return err
}

type NullableResourceRemoteInfoGithubOrg struct {
	value *ResourceRemoteInfoGithubOrg
	isSet bool
}

func (v NullableResourceRemoteInfoGithubOrg) Get() *ResourceRemoteInfoGithubOrg {
	return v.value
}

func (v *NullableResourceRemoteInfoGithubOrg) Set(val *ResourceRemoteInfoGithubOrg) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceRemoteInfoGithubOrg) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceRemoteInfoGithubOrg) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceRemoteInfoGithubOrg(val *ResourceRemoteInfoGithubOrg) *NullableResourceRemoteInfoGithubOrg {
	return &NullableResourceRemoteInfoGithubOrg{value: val, isSet: true}
}

func (v NullableResourceRemoteInfoGithubOrg) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceRemoteInfoGithubOrg) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


