/*
Opal API

The Opal API is a RESTful API that allows you to interact with the Opal Security platform programmatically.

API version: 1.0
Contact: hello@opal.dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package opal

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedBundleGroupList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedBundleGroupList{}

// PaginatedBundleGroupList struct for PaginatedBundleGroupList
type PaginatedBundleGroupList struct {
	// The cursor used to obtain the current result page.
	Previous *string `json:"previous,omitempty"`
	// The cursor with which to continue pagination if additional result pages exist.
	Next *string `json:"next,omitempty"`
	// The total number of items in the result set.
	TotalCount *int32 `json:"total_count,omitempty"`
	BundleGroups []BundleGroup `json:"bundle_groups"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedBundleGroupList PaginatedBundleGroupList

// NewPaginatedBundleGroupList instantiates a new PaginatedBundleGroupList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedBundleGroupList(bundleGroups []BundleGroup) *PaginatedBundleGroupList {
	this := PaginatedBundleGroupList{}
	this.BundleGroups = bundleGroups
	return &this
}

// NewPaginatedBundleGroupListWithDefaults instantiates a new PaginatedBundleGroupList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedBundleGroupListWithDefaults() *PaginatedBundleGroupList {
	this := PaginatedBundleGroupList{}
	return &this
}

// GetPrevious returns the Previous field value if set, zero value otherwise.
func (o *PaginatedBundleGroupList) GetPrevious() string {
	if o == nil || IsNil(o.Previous) {
		var ret string
		return ret
	}
	return *o.Previous
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedBundleGroupList) GetPreviousOk() (*string, bool) {
	if o == nil || IsNil(o.Previous) {
		return nil, false
	}
	return o.Previous, true
}

// HasPrevious returns a boolean if a field has been set.
func (o *PaginatedBundleGroupList) HasPrevious() bool {
	if o != nil && !IsNil(o.Previous) {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given string and assigns it to the Previous field.
func (o *PaginatedBundleGroupList) SetPrevious(v string) {
	o.Previous = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *PaginatedBundleGroupList) GetNext() string {
	if o == nil || IsNil(o.Next) {
		var ret string
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedBundleGroupList) GetNextOk() (*string, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *PaginatedBundleGroupList) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given string and assigns it to the Next field.
func (o *PaginatedBundleGroupList) SetNext(v string) {
	o.Next = &v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *PaginatedBundleGroupList) GetTotalCount() int32 {
	if o == nil || IsNil(o.TotalCount) {
		var ret int32
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginatedBundleGroupList) GetTotalCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *PaginatedBundleGroupList) HasTotalCount() bool {
	if o != nil && !IsNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *PaginatedBundleGroupList) SetTotalCount(v int32) {
	o.TotalCount = &v
}

// GetBundleGroups returns the BundleGroups field value
func (o *PaginatedBundleGroupList) GetBundleGroups() []BundleGroup {
	if o == nil {
		var ret []BundleGroup
		return ret
	}

	return o.BundleGroups
}

// GetBundleGroupsOk returns a tuple with the BundleGroups field value
// and a boolean to check if the value has been set.
func (o *PaginatedBundleGroupList) GetBundleGroupsOk() ([]BundleGroup, bool) {
	if o == nil {
		return nil, false
	}
	return o.BundleGroups, true
}

// SetBundleGroups sets field value
func (o *PaginatedBundleGroupList) SetBundleGroups(v []BundleGroup) {
	o.BundleGroups = v
}

func (o PaginatedBundleGroupList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedBundleGroupList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Previous) {
		toSerialize["previous"] = o.Previous
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.TotalCount) {
		toSerialize["total_count"] = o.TotalCount
	}
	toSerialize["bundle_groups"] = o.BundleGroups

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedBundleGroupList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bundle_groups",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedBundleGroupList := _PaginatedBundleGroupList{}

	err = json.Unmarshal(data, &varPaginatedBundleGroupList)

	if err != nil {
		return err
	}

	*o = PaginatedBundleGroupList(varPaginatedBundleGroupList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "previous")
		delete(additionalProperties, "next")
		delete(additionalProperties, "total_count")
		delete(additionalProperties, "bundle_groups")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedBundleGroupList struct {
	value *PaginatedBundleGroupList
	isSet bool
}

func (v NullablePaginatedBundleGroupList) Get() *PaginatedBundleGroupList {
	return v.value
}

func (v *NullablePaginatedBundleGroupList) Set(val *PaginatedBundleGroupList) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedBundleGroupList) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedBundleGroupList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedBundleGroupList(val *PaginatedBundleGroupList) *NullablePaginatedBundleGroupList {
	return &NullablePaginatedBundleGroupList{value: val, isSet: true}
}

func (v NullablePaginatedBundleGroupList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedBundleGroupList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


