name: Auto Release on PR Merge

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: minor

      - name: Create release
        run: |
          gh release create "${{ steps.tag_version.outputs.new_tag }}" \
            --title "${{ steps.tag_version.outputs.new_version }}" \
            --generate-notes \
            --verify-tag \
            --target "${{ github.sha }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
